import {createResolver} from '@nuxt/kit';
import categoryRoutesToPrerender from './data/category-routes.json'; // Assuming static list
import blogRoutesToPrerender from './data/blog-routes.json'; // Blog routes for prerendering

// Import product routes for prerendering (generated by build-sitemap.js)
let productRoutesToPrerender = [];
try {
  productRoutesToPrerender = require('./data/product-routes.json');
  console.log(`[Nuxt Config] Found ${productRoutesToPrerender.length} product routes to prerender.`);
} catch (error) {
  console.warn('[Nuxt Config] Product routes not found, will be generated during build.');
  productRoutesToPrerender = [];
}

// Import dynamic blog redirects (will be generated by build script)
let blogRedirects = {};
try {
  blogRedirects = require('./data/blog-redirects.json');
} catch (error) {
  console.warn('Blog redirects not found, using fallback redirects');
  blogRedirects = {
    '/best-inline-skates-2025': {
      redirect: {to: '/blog/best-inline-skates-2025', statusCode: 301},
    },
    '/roller-skating-toronto-guide': {
      redirect: {to: '/blog/roller-skating-toronto-guide', statusCode: 301},
    },
    '/skate-maintenance-winter': {
      redirect: {to: '/blog/skate-maintenance-winter', statusCode: 301},
    },
  };
}

const {resolve} = createResolver(import.meta.url);

console.log(`[Nuxt Config] Found ${categoryRoutesToPrerender.length} category routes to prerender from static file.`);
console.log(`[Nuxt Config] Found ${blogRoutesToPrerender.length} blog routes to prerender from static file.`);
console.log(`[Nuxt Config] Found ${Object.keys(blogRedirects).length} blog redirects configured.`);

export default defineNuxtConfig({
  extends: ['./woonuxt_base'],
  components: [{path: './components', pathPrefix: false, priority: 1000}],

  'graphql-client': {
    clients: {
      default: {
        host: process.env.GQL_HOST || '',
        corsOptions: {mode: 'cors', credentials: 'include'},
        headers: {
          'Content-Type': 'application/json',
          'X-Frontend-Type': 'woonuxt',
          'X-Requested-With': 'XMLHttpRequest',
          'Accept-Language': 'en-CA,en;q=0.9',
        },
        proxyCookies: true,
        proxy: true, // Force proxying through Nuxt server
      },
    },
    // Base-layer queries plus root-layer overrides/additions (e.g. getProductsForCards.gql,
    // which adds badge category slugs without editing woonuxt_base/).
    documentPaths: ['./woonuxt_base/app/queries', './queries'],
  },

  runtimeConfig: {
    // Server-only secrets
    stripeSecretKey: process.env.NUXT_STRIPE_SECRET_KEY,
    helcimApiToken: process.env.NUXT_HELCIM_API_TOKEN,
    wcConsumerKey: process.env.WC_CONSUMER_KEY,
    wcConsumerSecret: process.env.WC_CONSUMER_SECRET,
    // WordPress Application Password for admin GraphQL operations
    wpAdminUsername: process.env.WP_ADMIN_USERNAME,
    wpAdminAppPassword: process.env.WP_ADMIN_APP_PASSWORD,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    SENDING_EMAIL: process.env.SENDING_EMAIL,
    RECEIVING_EMAIL: process.env.RECEIVING_EMAIL,
    REVALIDATION_SECRET: process.env.REVALIDATION_SECRET,
    // Public config (available client+server/build)
    public: {
      stripePublishableKey: process.env.NUXT_STRIPE_PUBLISHABLE_KEY,
      wpBaseUrl: process.env.BASE_URL,
      exchangeRateApiKey: process.env.EXCHANGE_RATE_API_KEY || 'default_key',
      turnstyleSiteKey: process.env.TURNSTYLE_SITE_KEY,
      turnstyleSecretKey: process.env.TURNSTYLE_SECRET_KEY,
      turnstile: {
        siteKey: process.env.TURNSTYLE_SITE_KEY,
      },
      // --- NEW: Build-time fallback exchange rate ---
      // Provide a default value (e.g., 1.0) if the env var isn't set during build
      buildTimeExchangeRate: process.env.NUXT_PUBLIC_BUILD_TIME_EXCHANGE_RATE || '1.37',
      freeShippingThreshold: process.env.NUXT_PUBLIC_FREE_SHIPPING_THRESHOLD || '135',
      calculatorGraphqlEndpoint: process.env.NUXT_PUBLIC_CALCULATOR_GRAPHQL_ENDPOINT || 'https://proskatersplace.com/graphql',

      // --- Product Attribute Filters Configuration ---
      // These appear as filter options on category pages
      // 'categories' array controls which category slugs show this filter (empty = all categories)
      GLOBAL_PRODUCT_ATTRIBUTES: [
        // === GLOBAL FILTERS (show on all category pages) ===
        {
          slug: 'pa_manufacturer',
          label: 'Brand',
          type: 'brand', // Special searchable checkbox component
          showCount: true,
          hideEmpty: true,
          categories: [], // Empty = show on all categories
        },
        {
          slug: 'pa_colour',
          label: 'Colour',
          type: 'color', // Color swatch component
          showCount: true,
          hideEmpty: true,
          categories: [], // Empty = show on all categories
        },

        // === INLINE/ROLLER SKATING FILTERS ===
        {
          slug: 'pa_style',
          label: 'Skating Style',
          type: 'pill', // Pill/tag button component
          showCount: true,
          hideEmpty: true,
          categories: [
            'inline-skates',
            'roller-skates',
            'inline-skate-frames',
            'inline-skate-wheels',
            'roller-skate-wheels',
            'inline-skate-boots',
            'roller-skate-boots',
          ],
        },
        {
          slug: 'pa_fit',
          label: 'Fit',
          type: 'pill',
          showCount: true,
          hideEmpty: true,
          categories: ['inline-skates', 'roller-skates', 'inline-skate-boots', 'roller-skate-boots', 'ice-skates', 'figure-skates', 'hockey-skates'],
        },
        {
          slug: 'pa_wheelsize',
          label: 'Wheel Size',
          type: 'dropdown',
          showCount: true,
          hideEmpty: true,
          categories: ['inline-skates', 'inline-skate-wheels', 'inline-skate-frames'],
        },
        {
          slug: 'pa_length',
          label: 'Length',
          type: 'dropdown',
          showCount: true,
          hideEmpty: true,
          categories: ['inline-skates', 'roller-skates', 'inline-skate-frames'],
        },
        {
          slug: 'pa_size',
          label: 'Size',
          type: 'dropdown',
          showCount: true,
          hideEmpty: true,
          categories: ['inline-skates', 'roller-skates', 'ice-skates', 'figure-skates', 'hockey-skates', 'inline-skate-boots', 'roller-skate-boots'],
        },

        // === ALPINE/NORDIC SKIING FILTERS ===
        {
          slug: 'pa_skiing_style',
          label: 'Skiing Style',
          type: 'pill',
          showCount: true,
          hideEmpty: true,
          categories: ['alpine-skis', 'nordic-skis', 'cross-country-skis', 'ski-boots', 'ski-bindings', 'ski-poles'],
        },
        {
          slug: 'pa_flex',
          label: 'Flex',
          type: 'pill',
          showCount: true,
          hideEmpty: true,
          categories: ['alpine-skis', 'nordic-skis', 'cross-country-skis', 'ski-boots'],
        },
        {
          slug: 'pa_poleslength',
          label: 'Poles Length',
          type: 'dropdown',
          showCount: true,
          hideEmpty: true,
          categories: ['ski-poles', 'nordic-poles', 'cross-country-poles'],
        },
      ],
    },
  },

  devtools: {enabled: true},
  ssr: true,

  devServer: {
    /* ... */
  },

  nitro: {
    preset: 'cloudflare-pages',
    // Required by Wrangler 3.x to correctly resolve _worker.js directory format
    compatibilityDate: '2024-09-19',
    // Enable Node.js compatibility for Cloudflare Workers
    // Required for Node.js built-in modules (Buffer, events, util, etc.)
    compatibilityFlags: ['nodejs_compat'],
    storage: {
      cache: {driver: 'cloudflare-kv-binding', binding: 'NUXT_CACHE'},
      script_data: {
        driver: 'cloudflare-kv-binding',
        binding: 'NUXT_SCRIPT_DATA',
      },
      // Payment-critical records (stranded charges, duplicate-charge fingerprints, order
      // idempotency, Helcim failure beacons). Separate namespace so cache clears/rebuilds
      // (clear-kv-cache-safe.js wipes NUXT_CACHE completely) can never touch them.
      // The NUXT_PAYMENT_DATA KV binding must be added to the Pages project; until it is,
      // server/utils/paymentStorage.ts falls back to the cache store.
      payment: {driver: 'cloudflare-kv-binding', binding: 'NUXT_PAYMENT_DATA'},
      // Size-calculator funnel telemetry (Admin ▸ Calculator Stats). Same reasoning as `payment`:
      // the cache-clearing scripts wipe NUXT_CACHE and NUXT_SCRIPT_DATA completely, and analytics
      // history must survive a cache rebuild. The NUXT_STATS_DATA binding must be added to the
      // Pages project; until it is, server/utils/statsStorage.ts falls back to the script_data
      // store and scripts/clear-kv-cache-safe.js protects the `calc-stats:` prefix from deletion.
      stats: {driver: 'cloudflare-kv-binding', binding: 'NUXT_STATS_DATA'},
    },
    devStorage: {
      cache: {driver: 'fs', base: './.nuxt/dev-cache/isr'},
      script_data: {driver: 'fs', base: './.nuxt/dev-cache/script_data'},
      payment: {driver: 'fs', base: './.nuxt/dev-cache/payment'},
      stats: {driver: 'fs', base: './.nuxt/dev-cache/stats'},
    },
    prerender: {
      crawlLinks: false,
      routes: [
        '/',
        '/contact',
        '/terms',
        '/privacy',
        '/blog',
        '/roller-skates-size-calculator',
        ...(categoryRoutesToPrerender || []),
        ...(blogRoutesToPrerender || []),
        // Include product routes for prerendering (only if list is reasonable size)
        // For large product catalogs, rely on KV cache instead
        ...(productRoutesToPrerender && productRoutesToPrerender.length < 500 ? productRoutesToPrerender : []),
      ],
      ignore: [
        '/checkout/**',
        '/cart',
        '/account/**',
        '/api/_content/**', // Ignore Nuxt Content API routes
      ],
      concurrency: 10,
      interval: 1000,
      failOnError: false,
      autoSubfolderIndex: false,
    },
  },

  routeRules: {
    '/': {prerender: true, cache: {maxAge: 60 * 60 * 24, base: 'cache'}},
    '/blog': {
      prerender: true,
      cache: {maxAge: 60 * 60 * 24, base: 'cache'},
    },
    '/blog/**': {
      prerender: true,
      cache: {maxAge: 60 * 60 * 24 * 7, base: 'cache'},
    }, // Prerender all blog posts

    // Dynamic blog post redirects (generated at build time)
    ...blogRedirects,

    '/product-category/**': {
      prerender: true,
      cache: {maxAge: 60 * 60 * 24 * 7, base: 'cache'},
    }, // Rely on prerendering
    '/product/**': {cache: {maxAge: 60 * 60 * 72, base: 'cache'}}, // Use KV cache for products

    // Account/cart/checkout are client-only shells with no indexable content:
    // they were serving 200 with the homepage title and canonical, and no robots
    // directive at all (2026-07-23 audit). /search and bare /products are empty
    // SSR shells for the same reason. robots.txt Disallow alone does not deindex.
    '/cart': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/checkout/**': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/checkout': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/account/**': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/my-account/**': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/my-account': {ssr: false, headers: {'X-Robots-Tag': 'noindex, follow'}},
    '/search': {headers: {'X-Robots-Tag': 'noindex, follow'}},

    // Retired dev/duplicate pages (deleted 2026-07-23) — 301 the two that have a
    // real equivalent so Google swaps them rather than keeping duplicates indexed.
    '/privacy_new': {redirect: {to: '/privacy', statusCode: 301}},
    '/terms_backup': {redirect: {to: '/terms', statusCode: 301}},

    '/contact': {prerender: true},
    '/terms': {prerender: true},
    '/privacy': {prerender: true},
    '/inline-skates-size-calculator': {redirect: {to: '/roller-skates-size-calculator', statusCode: 301}},
    '/roller-skates-size-calculator': {
      prerender: true,
      cache: {maxAge: 60 * 60 * 24 * 7, base: 'cache'},
    },
  },

  hooks: {
    /* ... */
  },

  // ... (rest of your config) ...
  app: {
    head: {
      htmlAttrs: {
        lang: 'en-CA', // Canadian English
      },
      meta: [
        {charset: 'utf-8'},
        {name: 'viewport', content: 'width=device-width, initial-scale=1'},
        {name: 'format-detection', content: 'telephone=no'},
        // Geo-targeting for Canada
        {name: 'geo.region', content: 'CA'},
        {name: 'geo.placename', content: 'Canada'},
        {name: 'ICBM', content: '43.651070, -79.347015'}, // Toronto coordinates
        // Currency and pricing
        {property: 'product:price:currency', content: 'CAD'},
        {name: 'price_currency', content: 'CAD'},
        // Canadian-specific business info
        {name: 'business:location:country_name', content: 'Canada'},
        {name: 'business:location:region', content: 'Ontario'},
        {name: 'business:location:locality', content: 'Toronto'},
      ],
      link: [
        // NOTE (2026-07 hreflang repair): the static canonical + hreflang
        // cluster that used to live here shipped homepage URLs on EVERY page,
        // conflicting with the per-page tags from useCanadianSEO() (two
        // en-ca declarations with different hrefs invalidate the cluster).
        // Canonical + hreflang are per-page concerns — useCanadianSEO() owns
        // them exclusively now.
        // Preconnect to critical origins
        {
          rel: 'preconnect',
          href: 'https://proskatersplace.com',
          crossorigin: 'anonymous',
        },
        {
          rel: 'dns-prefetch',
          href: 'https://static.cloudflareinsights.com',
        },
      ],
      script: [
        // Structured data for Organization
        // NOTE: unhead v2 (Nuxt >= 3.16) removed the `children` prop — use
        // innerHTML, otherwise the script tag renders empty
        // Single site-wide business entity.
        // Until 2026-07-23 the homepage carried TWO conflicting Organization
        // nodes — this one (name "ProSkaters Place Canada", no @id, city-only
        // address) and one in pages/index.vue (@id #organization, full street
        // address, telephone, sameAs, but a logo that 404'd). Google was handed
        // two competing brand entities. Consolidated here, keyed by @id so the
        // WebSite node in pages/index.vue still resolves its publisher.
        //
        // @type SportingGoodsStore is a subtype of both Organization and
        // LocalBusiness, so the real Etobicoke retail location earns local
        // signals — and currenciesAccepted/paymentAccepted become valid
        // properties (they are not defined on bare Organization).
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'SportingGoodsStore',
            '@id': 'https://proskatersplace.ca/#organization',
            name: 'ProSkaters Place',
            alternateName: 'ProSkaters Place Canada',
            url: 'https://proskatersplace.ca',
            logo: 'https://proskatersplace.ca/logo.svg',
            image: 'https://proskatersplace.ca/logo.svg',
            description:
              "Canada's most trusted online skate shop specializing in inline skates, roller skates, protective gear, and skating accessories. Serving Toronto and all of Canada since 2011.",
            telephone: '+1-416-739-2929',
            address: {
              '@type': 'PostalAddress',
              streetAddress: '110 Galaxy Blvd',
              addressLocality: 'Etobicoke',
              addressRegion: 'ON',
              postalCode: 'M9W 4Y6',
              addressCountry: 'CA',
            },
            contactPoint: {
              '@type': 'ContactPoint',
              telephone: '+1-416-739-2929',
              contactType: 'customer service',
              areaServed: 'CA',
              availableLanguage: ['English', 'French'],
            },
            sameAs: ['https://www.facebook.com/proskatersplace', 'https://www.instagram.com/proskatersplace'],
            currenciesAccepted: 'CAD',
            paymentAccepted: ['Credit Card', 'PayPal', 'Interac'],
            areaServed: {
              '@type': 'Country',
              name: 'Canada',
            },
          }),
        },
        // Cloudflare Turnstile for spam protection
        {
          src: 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit',
          defer: true,
        },
      ],
    },
  },

  modules: ['nuxt-gtag', '@nuxt/content', '@nuxtjs/i18n'],

  // Nuxt Image optimization configuration
  // DISABLED: Causing issues with Cloudflare Pages - images not loading
  // Using regular <img> tags instead for better compatibility
  image: {
    provider: 'none', // Disable image optimization
    quality: 80,
    format: ['jpeg', 'png', 'webp'],
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
      xl: 1280,
      xxl: 1536,
    },
    domains: ['proskatersplace.com', 'proskatersplace.ca', 'www.proskatersplace.com'],
  },

  // i18n configuration - Canadian locale
  i18n: {
    locales: [
      {code: 'en', file: 'en.json', name: 'English (Base)', iso: 'en'},
      {code: 'en-CA', file: 'en-CA.json', name: 'English (Canada) 🇨🇦', iso: 'en-CA'},
      {code: 'en-US', file: 'en-US.json', name: 'English 🇺🇸', iso: 'en-US'},
      {code: 'fr-CA', file: 'fr-CA.json', name: 'Français (Canada) 🇨🇦', iso: 'fr-CA'},
    ],
    langDir: './locales',
    defaultLocale: 'en-CA',
    strategy: 'no_prefix',
    detectBrowserLanguage: false,
    compilation: {
      strictMessage: false,
      escapeHtml: false,
    },
    vueI18n: './i18n.config.ts',
  },

  // Content module configuration for SEO
  content: {
    documentDriven: false,
    highlight: {
      theme: 'github-light',
    },
    markdown: {
      anchorLinks: false,
    },
    experimental: {
      clientDB: true, // Enable client-side database to prevent 404s
    },
    ignores: [
      '/product-category', // Ignore product category routes (from WordPress)
      '/product', // Ignore product routes (from WordPress)
      '/my-account', // Ignore account routes
      '/checkout', // Ignore checkout routes
    ],
  },

  // SEO and localization improvements for .ca site
  // Note: Content module configuration is handled automatically
});
