import { createResolver } from "@nuxt/kit";
import categoryRoutesToPrerender from "./data/category-routes.json"; // Assuming static list
import blogRoutesToPrerender from "./data/blog-routes.json"; // Blog routes for prerendering

// Import dynamic blog redirects (will be generated by build script)
let blogRedirects = {};
try {
  blogRedirects = require("./data/blog-redirects.json");
} catch (error) {
  console.warn("Blog redirects not found, using fallback redirects");
  blogRedirects = {
    "/best-inline-skates-2025": {
      redirect: { to: "/blog/best-inline-skates-2025", statusCode: 301 },
    },
    "/roller-skating-toronto-guide": {
      redirect: { to: "/blog/roller-skating-toronto-guide", statusCode: 301 },
    },
    "/skate-maintenance-winter": {
      redirect: { to: "/blog/skate-maintenance-winter", statusCode: 301 },
    },
  };
}

const { resolve } = createResolver(import.meta.url);

console.log(
  `[Nuxt Config] Found ${categoryRoutesToPrerender.length} category routes to prerender from static file.`
);
console.log(
  `[Nuxt Config] Found ${blogRoutesToPrerender.length} blog routes to prerender from static file.`
);
console.log(
  `[Nuxt Config] Found ${Object.keys(blogRedirects).length} blog redirects configured.`
);

export default defineNuxtConfig({
  extends: ["./woonuxt_base"],
  components: [{ path: "./components", pathPrefix: false, priority: 1000 }],

  runtimeConfig: {
    // Server-only secrets
    stripeSecretKey: process.env.NUXT_STRIPE_SECRET_KEY,
    helcimApiToken: process.env.NUXT_HELCIM_API_TOKEN,
    wcConsumerKey: process.env.WC_CONSUMER_KEY,
    wcConsumerSecret: process.env.WC_CONSUMER_SECRET,
    // WordPress Application Password for admin GraphQL operations
    wpAdminUsername: process.env.WP_ADMIN_USERNAME,
    wpAdminAppPassword: process.env.WP_ADMIN_APP_PASSWORD,
    SENDGRID_API_KEY: process.env.SENDGRID_API_KEY,
    SENDING_EMAIL: process.env.SENDING_EMAIL,
    RECEIVING_EMAIL: process.env.RECEIVING_EMAIL,
    REVALIDATION_SECRET: process.env.REVALIDATION_SECRET,
    // Public config (available client+server/build)
    public: {
      stripePublishableKey: process.env.NUXT_STRIPE_PUBLISHABLE_KEY,
      wpBaseUrl: process.env.BASE_URL,
      exchangeRateApiKey: process.env.EXCHANGE_RATE_API_KEY || "default_key",
      turnstyleSiteKey: process.env.TURNSTYLE_SITE_KEY,
      turnstyleSecretKey: process.env.TURNSTYLE_SECRET_KEY,
      turnstile: {
        siteKey: process.env.TURNSTYLE_SITE_KEY,
      },
      // --- NEW: Build-time fallback exchange rate ---
      // Provide a default value (e.g., 1.0) if the env var isn't set during build
      buildTimeExchangeRate:
        process.env.NUXT_PUBLIC_BUILD_TIME_EXCHANGE_RATE || "1.37",
    },
  },

  devtools: { enabled: true },
  ssr: true,

  devServer: {
    /* ... */
  },

  nitro: {
    preset: "cloudflare-pages",
    storage: {
      cache: { driver: "cloudflare-kv-binding", binding: "NUXT_CACHE" },
      script_data: {
        driver: "cloudflare-kv-binding",
        binding: "NUXT_SCRIPT_DATA",
      },
    },
    devStorage: {
      cache: { driver: "fs", base: "./.nuxt/dev-cache/isr" },
      script_data: { driver: "fs", base: "./.nuxt/dev-cache/script_data" },
    },
    prerender: {
      crawlLinks: false,
      routes: [
        "/",
        "/contact",
        "/terms",
        "/privacy",
        "/blog",
        ...(categoryRoutesToPrerender || []),
        ...(blogRoutesToPrerender || []),
      ],
      ignore: ["/product/**", "/checkout/**", "/cart", "/account/**"],
      concurrency: 10,
      interval: 1000,
      failOnError: false,
      autoSubfolderIndex: false,
    },
  },

  routeRules: {
    "/": { prerender: true, cache: { maxAge: 60 * 60 * 24, base: "cache" } },
    "/blog": {
      prerender: true,
      cache: { maxAge: 60 * 60 * 24, base: "cache" },
    },
    "/blog/**": {
      prerender: true,
      cache: { maxAge: 60 * 60 * 24 * 7, base: "cache" },
    }, // Prerender all blog posts

    // Dynamic blog post redirects (generated at build time)
    ...blogRedirects,

    "/product-category/**": {
      prerender: true,
      cache: { maxAge: 60 * 60 * 24 * 7, base: "cache" },
    }, // Rely on prerendering
    "/product/**": { cache: { maxAge: 60 * 60 * 72, base: "cache" } }, // Use KV cache for products
    "/checkout/**": { ssr: false },
    "/cart": { ssr: false },
    "/account/**": { ssr: false },
    "/contact": { prerender: true },
    "/terms": { prerender: true },
    "/privacy": { prerender: true },
  },

  hooks: {
    /* ... */
  },

  // ... (rest of your config) ...
  app: {
    head: {
      htmlAttrs: {
        lang: "en-CA", // Canadian English
      },
      meta: [
        { charset: "utf-8" },
        { name: "viewport", content: "width=device-width, initial-scale=1" },
        { name: "format-detection", content: "telephone=no" },
        // Geo-targeting for Canada
        { name: "geo.region", content: "CA" },
        { name: "geo.placename", content: "Canada" },
        { name: "ICBM", content: "43.651070, -79.347015" }, // Toronto coordinates
        // Currency and pricing
        { property: "product:price:currency", content: "CAD" },
        { name: "price_currency", content: "CAD" },
        // Canadian-specific business info
        { name: "business:location:country_name", content: "Canada" },
        { name: "business:location:region", content: "Ontario" },
        { name: "business:location:locality", content: "Toronto" },
      ],
      link: [
        { rel: "canonical", href: "https://proskatersplace.ca" },
        // Hreflang for international targeting
        {
          rel: "alternate",
          hreflang: "en-ca",
          href: "https://proskatersplace.ca",
        },
        {
          rel: "alternate",
          hreflang: "en-us",
          href: "https://proskatersplace.com",
        },
        {
          rel: "alternate",
          hreflang: "x-default",
          href: "https://proskatersplace.com",
        },
      ],
      script: [
        // Structured data for Organization
        {
          type: "application/ld+json",
          children: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Organization",
            name: "ProSkaters Place Canada",
            url: "https://proskatersplace.ca",
            logo: "https://proskatersplace.ca/logo.svg",
            description:
              "Canada's premier destination for inline skates, roller skates, and skating accessories. Expert advice and fast shipping across Canada.",
            address: {
              "@type": "PostalAddress",
              addressCountry: "CA",
              addressRegion: "ON",
              addressLocality: "Toronto",
            },
            contactPoint: {
              "@type": "ContactPoint",
              contactType: "customer service",
              availableLanguage: ["English", "French"],
            },
            currenciesAccepted: "CAD",
            paymentAccepted: ["Credit Card", "PayPal", "Interac"],
            areaServed: {
              "@type": "Country",
              name: "Canada",
            },
          }),
        },
      ],
    },
  },

  modules: ["nuxt-gtag", "@nuxt/content"],

  // Content module configuration for SEO
  content: {
    documentDriven: true,
    highlight: {
      theme: "github-light",
    },
    markdown: {
      anchorLinks: false,
    },
  },

  // SEO and localization improvements for .ca site
  // Note: Content module configuration is handled automatically
});
