// ─── 1. Register meta fields with WP REST API ────────────────────────────────

add_action( 'init', function() {
    // --- PSP custom fields ---
    register_term_meta( 'pwb-brand', 'psp_brand_content', [
        'show_in_rest'      => true,
        'single'            => true,
        'type'              => 'string',
        'sanitize_callback' => 'wp_kses_post',
        'auth_callback'     => function() {
            return current_user_can( 'manage_woocommerce' );
        },
        'description'       => 'Long-form brand content (description, FAQs). Renders below product grid.',
    ] );

    register_term_meta( 'pwb-brand', 'psp_brand_schema', [
        'show_in_rest'      => true,
        'single'            => true,
        'type'              => 'string',
        'sanitize_callback' => 'sanitize_textarea_field',
        'auth_callback'     => function() {
            return current_user_can( 'manage_woocommerce' );
        },
        'description'       => 'FAQPage JSON-LD schema — emitted in wp_head on brand archive pages.',
    ] );

    // --- Rank Math SEO fields ---
    // Rank Math uses these internally but doesn't always register them with
    // show_in_rest for custom taxonomies. Explicit registration ensures our
    // optimize-brand-page.js script can write them via the WP REST API.
    $rank_math_keys = [
        'rank_math_title',
        'rank_math_description',
        'rank_math_focus_keyword',
    ];
    foreach ( $rank_math_keys as $key ) {
        register_term_meta( 'pwb-brand', $key, [
            'show_in_rest'      => true,
            'single'            => true,
            'type'              => 'string',
            'sanitize_callback' => 'sanitize_text_field',
            'auth_callback'     => function() {
                return current_user_can( 'manage_woocommerce' );
            },
        ] );
    }
} );

// ─── 2. Add fields to brand edit screen ──────────────────────────────────────

add_action( 'pwb-brand_edit_form_fields', function( $term ) {
    $content = get_term_meta( $term->term_id, 'psp_brand_content', true );
    $schema  = get_term_meta( $term->term_id, 'psp_brand_schema', true );
    ?>
    <tr class="form-field">
        <th scope="row">
            <label for="psp_brand_content">SEO Brand Content</label>
        </th>
        <td>
            <?php
            wp_editor(
                wp_kses_post( $content ?: '' ),
                'psp_brand_content',
                [
                    'textarea_name' => 'psp_brand_content',
                    'textarea_rows' => 15,
                    'media_buttons' => false,
                ]
            );
            ?>
            <p class="description">
                Long-form SEO content generated by <code>optimize-brand-page.js</code>.<br>
                Renders <strong>below the product grid</strong>. Includes brand description, FAQs, and internal links.
            </p>
        </td>
    </tr>
    <tr class="form-field">
        <th scope="row">
            <label for="psp_brand_schema">FAQPage Schema (JSON-LD)</label>
        </th>
        <td>
            <textarea id="psp_brand_schema" name="psp_brand_schema" rows="6" style="width:100%;font-family:monospace;font-size:12px;"><?php echo esc_textarea( $schema ?: '' ); ?></textarea>
            <p class="description">FAQPage JSON-LD — output in <code>&lt;head&gt;</code> on this brands archive page.</p>
        </td>
    </tr>
    <?php
}, 10, 1 );

// ─── 3. Save fields on term edit ─────────────────────────────────────────────

add_action( 'edited_pwb-brand', function( $term_id ) {
    if ( ! current_user_can( 'manage_woocommerce' ) ) return;

    if ( isset( $_POST['psp_brand_content'] ) ) {
        update_term_meta(
            $term_id,
            'psp_brand_content',
            wp_kses_post( wp_unslash( $_POST['psp_brand_content'] ) )
        );
    }

    if ( isset( $_POST['psp_brand_schema'] ) ) {
        update_term_meta(
            $term_id,
            'psp_brand_schema',
            sanitize_textarea_field( wp_unslash( $_POST['psp_brand_schema'] ) )
        );
    }
} );

// ─── 4. Render content below product grid on brand archive pages ──────────────

add_action( 'woocommerce_after_shop_loop', function() {
    if ( ! is_tax( 'pwb-brand' ) ) return;

    $term = get_queried_object();
    if ( ! $term ) return;

    $content = get_term_meta( $term->term_id, 'psp_brand_content', true );
    if ( empty( $content ) ) return;

    echo '<div class="psp-brand-content" style="margin-top:3rem;padding-top:2rem;border-top:1px solid #eee;">';
    echo wp_kses_post( $content );
    echo '</div>';
}, 20 );

// ─── 5. Output FAQPage schema in <head> ──────────────────────────────────────

add_action( 'wp_head', function() {
    if ( ! is_tax( 'pwb-brand' ) ) return;

    $term = get_queried_object();
    if ( ! $term ) return;

    $schema = get_term_meta( $term->term_id, 'psp_brand_schema', true );
    if ( empty( $schema ) ) return;

    $decoded = json_decode( $schema );
    if ( ! $decoded ) return;

    echo "\n<script type=\"application/ld+json\">\n";
    echo wp_json_encode( $decoded, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT );
    echo "\n</script>\n";
} );

// ─── 6. REST API: brand termmeta diagnostic & cleanup ─────────────────────────
//
// GET  /wp-json/psp/v1/brand-meta/<term_id>            → all termmeta (debug)
// DELETE /wp-json/psp/v1/brand-meta/<term_id>/<key>     → delete a specific key
// POST /wp-json/psp/v1/brand-clear-old/<term_id>        → clear known old-content keys
//
add_action( 'rest_api_init', function() {

    // 6a. List ALL termmeta for a brand term (diagnostic)
    register_rest_route( 'psp/v1', '/brand-meta/(?P<id>\d+)', [
        'methods'             => 'GET',
        'permission_callback' => function() { return current_user_can( 'manage_woocommerce' ); },
        'callback'            => function( WP_REST_Request $request ) {
            $term_id = (int) $request['id'];
            $term    = get_term( $term_id, 'pwb-brand' );
            if ( ! $term || is_wp_error( $term ) ) {
                return new WP_Error( 'invalid_term', 'Term not found', [ 'status' => 404 ] );
            }
            $all_meta = get_term_meta( $term_id );
            $summary  = [];
            foreach ( $all_meta as $key => $values ) {
                $val = count( $values ) === 1 ? $values[0] : $values;
                $summary[ $key ] = [
                    'value'  => is_string( $val ) ? mb_substr( $val, 0, 300 ) : $val,
                    'length' => is_string( $val ) ? mb_strlen( $val ) : null,
                ];
            }
            return rest_ensure_response( [
                'term_id' => $term_id,
                'name'    => $term->name,
                'slug'    => $term->slug,
                'meta'    => $summary,
            ] );
        },
    ] );

    // 6b. Delete a single meta key by name
    register_rest_route( 'psp/v1', '/brand-meta/(?P<id>\d+)/(?P<key>[a-zA-Z0-9_-]+)', [
        'methods'             => 'DELETE',
        'permission_callback' => function() { return current_user_can( 'manage_woocommerce' ); },
        'callback'            => function( WP_REST_Request $request ) {
            $term_id = (int) $request['id'];
            $key     = sanitize_key( $request['key'] );
            $before  = get_term_meta( $term_id, $key, true );
            $deleted = delete_term_meta( $term_id, $key );
            return rest_ensure_response( [
                'deleted'      => $deleted,
                'key'          => $key,
                'had_value'    => ! empty( $before ),
                'value_length' => is_string( $before ) ? mb_strlen( $before ) : 0,
            ] );
        },
    ] );

    // 6c. Clear all known old/orphaned PWB content meta keys for a brand term
    register_rest_route( 'psp/v1', '/brand-clear-old/(?P<id>\d+)', [
        'methods'             => 'POST',
        'permission_callback' => function() { return current_user_can( 'manage_woocommerce' ); },
        'callback'            => function( WP_REST_Request $request ) {
            $term_id = (int) $request['id'];
            // Known old content meta keys from PWB and generic SEO plugins
            $old_keys = [
                'pwb_brand_desc',
                'pwb_brand_content',
                'second_description',
                'brand_content',
                'brand_description',
                'pwb_desc_2',
                'pwb_brand_banner',
                'pwb_brand_banner_link',
                // Old Yoast (if any)
                '_yoast_wpseo_title',
                '_yoast_wpseo_metadesc',
                '_yoast_wpseo_focuskw',
            ];
            $cleared = [];
            foreach ( $old_keys as $key ) {
                $val = get_term_meta( $term_id, $key, true );
                if ( ! empty( $val ) ) {
                    delete_term_meta( $term_id, $key );
                    $cleared[] = $key;
                }
            }
            return rest_ensure_response( [
                'term_id' => $term_id,
                'cleared' => $cleared,
                'count'   => count( $cleared ),
            ] );
        },
    ] );
} );

// ─── 7. Suppress old Elementor brand content when psp_brand_content exists ────
//
// Problem: Old brand pages have an Elementor template with generic/AI text that
// renders alongside our optimized content. When our field is populated, inject
// CSS to hide the old Elementor content section.
//
// This is a temporary bridge until the theme LLM properly removes/conditionalizes
// the Elementor brand archive template.
//
add_action( 'wp_head', function() {
    if ( ! is_tax( 'pwb-brand' ) ) return;

    $term = get_queried_object();
    if ( ! $term ) return;

    $our_content = get_term_meta( $term->term_id, 'psp_brand_content', true );
    if ( empty( $our_content ) ) return;

    // When our optimized content exists, hide the old Elementor-rendered content
    // that sits ABOVE our psp-brand-content div. We target the Elementor section
    // that contains the old brand description text.
    ?>
    <style id="psp-hide-old-brand-content">
        /* Hide old Elementor brand content block when PSP optimized content is present */
        .tax-pwb-brand .elementor-widget-text-editor:not(.psp-keep) {
            display: none !important;
        }
        /* Also hide any duplicate in theme-builder rendered sections */
        .tax-pwb-brand .brand-description-old,
        .tax-pwb-brand .pwb-brand-description-bottom {
            display: none !important;
        }
    </style>
    <?php
}, 5 );