<template>
  <div class="flex items-center justify-center min-h-screen p-[50px]">
    <div class="max-w-3xl w-full">
      <h1 class="mb-8 text-3xl font-semibold text-primary text-center">
        Terms & Conditions
      </h1>
      <div class="container grid md:grid-cols-1 lg:grid-cols-1">
        <div class="w-full">
          <div class="prose mx-auto">
            <!-- Changed line -->
            <h4>Dear Clients…</h4>
            <p>
              Your satisfaction with our products and service is our TOP
              priority and we would go an extra mile to assure that. Please
              familiarize yourself with these policies to avoid
              misunderstandings and possible future disappointments! We are a
              dynamic company and do realize that without our loyal clients and
              referrals we wouldn’t exist, so we are always open for suggestions
              and would do our best to accommodate your requests. Having said
              that, our terms and conditions are dictated by financial costs
              associated with shipping rates and other related expenses.
            </p>
            <h3>CURBSIDE PICKUP</h3>
            <p>
              Your satisfaction with our products and service is our TOP
              priority and we would go an extra mile to assure that. Please
              familiarize yourself with these policies to avoid
              misunderstandings and possible future disappointments! We are a
              dynamic company and do realize that without our loyal clients and
              referrals we wouldn’t exist, so we are always open for suggestions
              and would do our best to accommodate your requests. Having said
              that, our terms and conditions are dictated by financial costs
              associated with shipping rates and other related expenses.
            </p>

            <h3>EXCHANGE POLICY (excluding Skis)</h3>
            <p>
              In case you would need to exchange an item, we would gladly work
              with you to assure your complete satisfaction with our service. We
              offer FREE return shipping for an exchange (contiguous USA and
              Canada clients only) on items over $100 in value excluding
              Clearance items. Please see our Clearance Items Section below!
              Custom-made and special order products may not qualify for
              exchanges. Please contact us via email
              (customerservice@proskatersplace.com) within 60 days of purchase
              to assure that we have the other item/skate size in stock. The
              originally purchased item will have to be brand-new (unused) and
              returned with no signs of use, clean, and with no scratches. The
              original packaging will be required (if applicable). US clients
              (Contiguous States): For any items, a UPS return shipping label
              will have to be generated by us and it will be forwarded to you
              via email. If the product value is over $100, the return shipping
              cost will be covered by ProSkaters Place, if it is under US$100,
              the client will have to cover its cost (US$15). Once the product
              is received and inspected, the new one will be shipped out with
              the appropriate shipping option to you. Please note that the
              replacement item shipping cost will be at the client’s expense
              (usually US$15) and will have to be charged prior to the shipment
              via electronic invoice. Only one size exchange will be covered by
              us for the items over US$100 in price, while the rest of the
              shipments back and forth will have to be covered by the client
              (usually US$30 in total). Canadian clients: For any items, a UPS
              return shipping label will have to be generated by us and it will
              be forwarded to you via email (unless advised overwise by our
              Customer Service). Once the product is received and inspected, the
              new one will be shipped out with the appropriate shipping option
              to you. Please note that the replacement item shipping cost will
              be at the client’s expense (usually CA$18) and will have to be
              charged prior to the shipment via electronic invoice. Clients in
              other countries: For any items, the client will need to ship them
              back to our warehouse in Toronto, Ontario with any shipping
              service that is the most convenient and least expensive to the
              client, as the cost will have to be covered by the shipper. Our
              Customer Service can also check optional return shipping rates via
              our Courier accounts as they may be less expensive. The maximum
              value of the package has to be set at US$100 as overwise Customs
              fees will apply. Once the product is received and inspected, a
              replacement item will be secured and the actual shipping cost will
              be charged via electronic invoice. Any item(s) not meeting the
              above requirements will not be accepted and the customer
              responsible for return shipping. A copy of your invoice is helpful
              but not mandatory. Sorry, but we are unable to offer the Free
              Return for an exchange shipping service to our international
              clients (outside of the USA and Canada) due to the high cost of
              shipping.
            </p>
            <h3>RETURN POLICY (excluding Skis)</h3>
            <p>
              In case you would need to return an item, we would gladly work
              with you to ensure your complete satisfaction with our service.
              The following policy does not apply to Clearance Items.
              Custom-made and special order products do not qualify for returns.
              Please contact us via email (customerservice@proskatersplace.com)
              within 60 days of purchase. The originally purchased item will
              have to be brand-new (unused) and returned with no signs of use,
              clean, and with no scratches. The original packaging will be
              required (if applicable). For your convenience, we are not
              charging restocking or handling fees! US clients (Contiguous
              States): For any items, a UPS return shipping label will have to
              be generated by us and it will be forwarded to you via email. Once
              the product is received and inspected, a refund will be issued. If
              the item was shipped to you and the order has qualified for the
              Free Shipping option, the original shipping cost as well the cost
              of the return shipment would be deducted from the refund amount
              (usually US$30 in total). If the original shipment was paid for,
              this amount will not be refunded as well as the cost of the return
              shipment (usually US$18) will be deducted from the refund.
              Canadian clients: For any items, a UPS return shipping label will
              have to be generated by us and it will be forwarded to you via
              email (unless advised overwise by our Customer Service). Once the
              product received and inspected, a refund will be issued. If the
              item was shipped to you and the order has qualified for the Free
              Shipping option, the original shipping cost as well the cost of
              the return shipment would be deducted from the refund amount
              (usually CA$40 in total). If the original shipment was paid for,
              this amount will not be refunded as well as the cost of the return
              shipment (usually CA$25) will be deducted from the refund. Clients
              in other countries: For any items, the client will need to ship it
              back to our warehouse in Toronto, Ontario with any shipping
              service that is the most convenient and least expensive to the
              client, as the cost will have to be covered by the shipper. Our
              Customer Service can also check optional return shipping rates via
              our Courier accounts as they may be less expensive. The maximum
              value of the package has to be set at US$100 as otherwise Customs
              fees will apply. Once the product received and inspected, a refund
              will be issued. The original shipping cost will be deducted from
              the refund. Please kindly let us know the reason for the return,
              so we will be able to learn and improve for the next time! Please
              make sure that: Your item should be brand-new and can be sold
              again as new. Item(s) must be in original packaging without any
              tags removed. Item(s) cannot be used, scuffed, sharpened, washed,
              smelling of odor, etc… The packaging is not damaged or missing. No
              tape, stickers, shipping labels, or other foreign objects can be
              attached to the box. Any item(s) not meeting the above
              requirements will not be accepted and the customer responsible for
              return shipping. A copy of your invoice is helpful but not
              mandatory.
            </p>
            <h3>SKIS EXCHANGE / RETURN POLICY</h3>
            <p>
              In order to prevent any skis damaging during shipment, new skis
              return for refund or exchange will be possible only when bringing
              it to the shop in person. No returns via shipment will be
              accepted. Please perform all necessary measurements and
              validations before placing your order online! When a ski is
              returned for refund/exchange in store, a $20 restocking fee will
              apply. If the ski was shipped to a client and then returned in
              person for refund, a $40 (restocking fee + shipment expense) will
              be deduced from the refunded sum.
            </p>
            <h3>CLEARANCE ITEMS POLICY</h3>
            <p>
              The items that have a “Clearance” tag on the product photo and/or
              that have prices ending with .79 in USD are on Clearance and will
              no longer be carried by our shop. Therefore, these items are
              available on a first-come-first-serve basis and can not be
              backordered. These items also do not qualify for the PSP Rewards!
              Due to a super low sales margin on these items and quite often a
              loss, we can not provide free returns for an exchange. We
              understand that buying online is sometimes tricky and therefore
              ready to accept these items back for an exchange. In this case,
              the client will have to cover the costs of back and forth
              shipments (usually a total of US$30 / CAD$40) per pair of skates).
              The replacement pair will be shipped under the same rules as a new
              order would (a.k.a free shipping if applicable). Under no
              circumstances, the clearance items will be accepted for a refund!
              An exchange or a store credit will be issued for the purchase
              amount minus the back and forth shipping costs.
            </p>
            <h3>PRICE MATCH POLICY</h3>
            <p>
              At ProSkaters Place we always strive to provide the best possible
              prices for our valued customers upfront. If accidentally there is
              an exception and you find a lower price for an identical item in
              another store or online prior to placing an order, please see the
              rules below to check if it qualifies for the Price Match. We also
              provide a grace period of 7 days from the original purchase date
              to apply for a Price Match under the same terms. No price match
              will be available after that period. The competitor should be a
              legitimate store or online shop with verifiable contact details
              and located within North America The product should be identical
              in all features, size, colors, and other specifications The
              product and size must be IN STOCK on the competitor’s website or
              in-store (the proof is required if not available for online
              verification) We will carefully review and verify all the
              supporting information. Please allow us up to 48 hours to process
              your request and advise you on our decision. Please note that is
              some extreme cases, we reserve the right to refuse to provide a
              price match, and this only if it will cause us to lose money on
              that sale. The following items DO NOT qualify for the price match:
              Clearance, closeout, and liquidation items on our or competitor’s
              website Products listed on Amazon, Bay.com, Aliexpress, or any
              other internet selling platform of this type Any client-specific
              deals, vouchers and/or one-time promotions offered by a competitor
              The price match service is not available at the time of the
              storewide promotional period – Boxing week, Christmas, etc… Please
              note: the price match will take into account the sale terms
              including shipping, delivery fees, rewards, and taxes that might
              apply from a competitor’s website. For example, if the product
              cost on the competitor’s website is $100 and the shipping is an
              extra $30, the match will be up to $130. any additional rewards
              and sales promotions will be waived on price matched items.
            </p>
            <h3>WARRANTY</h3>
            <p>
              All of the products qualify for a manufacturing warranty against
              the defects accordingly to the specific manufacturer terms and
              conditions. ProSkaters Place will gladly represent the client and
              lead every case to the best possible resolution with the
              manufacturer. Under no circumstances, ProSkates Place will be
              liable to any claims or fees. We will work with you and for you
              but please mind that we are merely a reseller and cannot be
              responsible for manufacturer mistakes.
            </p>
            <h3>CUSTOMIZATION POLICY</h3>
            <p>
              Our shop is one of very few in the world that provides product
              customization services. We do our best to stock most of the
              components in sufficient quantities, but while we will do our best
              we can not guarantee the customization parts availability. Wrong
              color of the wheels or any other parts on skates nor an upgrade
              that has been not performed will NOT qualify skates for free
              return shipping for either exchange or return. We gladly will
              refund the upgrade fee (if it has been charged) and will try to
              work with you to fix the issue. ProSkaters Place Inc reserves the
              right to end or change these terms at any time without prior
              notice. Effective January 1st, 2024.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
