<template>
  <div class="flex items-center justify-center min-h-screen p-[50px]">
    <div class="max-w-3xl w-full">
      <h1 class="mb-8 text-3xl font-semibold text-primary text-center">
        Terms & Conditions
      </h1>
      <div class="container grid md:grid-cols-1 lg:grid-cols-1">
        <div class="w-full">
          <div class="prose mx-auto">
            <h4>Dear Clients…</h4>
            <p>
              Your satisfaction with our products and service is our TOP priority, and we will go the extra mile to ensure that. Please familiarize yourself with these policies to avoid misunderstandings and possible future disappointments! We are a dynamic company that recognizes the importance of our loyal clients and referrals. Therefore, we are always open to suggestions and would do our best to accommodate your requests. Having said that, our terms and conditions are dictated by financial costs associated with shipping rates and other related expenses.
            </p>
            <h3>EXCHANGE POLICY (excluding Skis, Poles, and Clearance items)</h3>
            <p>
              If you need to exchange an item, we will gladly work with you to ensure your complete satisfaction with our service.
            </p>
            <p>
              We offer FREE return shipping for exchanges to our US clients on any items valued over $150, excluding Clearance items. Custom-made and special-order products do not qualify for returns or exchanges.
            </p>
            <p>
              Please send us an email to customerservice@proskatersplace.com within 60 days of purchase to notify us of the need and to ensure that we have the other item/skate size in stock. The originally purchased item must be brand-new (unused) and returned in its original condition, clean, with no signs of use or scratches. Original packaging will be required (if applicable).
            </p>
            <p>
              For any items, a return shipping label can be generated by us upon request and emailed to you. If the client can exchange the product at the Toronto store, there are not going to be any fees or charges. If the client prefers to ship the products by Canada Post or other shipping service at his/her expense to the Toronto shop, an authorization from Customer Service has to be received first. If the product value exceeds $150, the return can be done only via a shipping label generated by our Customer Service, and the cost will be covered by ProSkaters Place. If it is under $150, the client will have to cover the cost ($18) or ship at his/her expense. Once the product is received and inspected, the new one will be shipped out with the appropriate shipping option to you. Please note that the shipping cost of the replacement item will be at the client's expense (typically $20) and must be paid prior to shipment. Only one size exchange will be covered by us for items priced over $150, while the rest of the shipments back and forth will have to be covered by the client (usually $36).
            </p>
            <p>
              Any item(s) not meeting the above requirements will not be accepted, and the customer is responsible for the return shipping. A copy of your invoice is helpful but not mandatory. Sorry, but we are unable to offer free return shipping for exchange services to our international clients (outside of the USA) due to the high cost of shipping.
            </p>
            <h3>RETURN POLICY (excluding Skis, Poles, and Clearance items)</h3>
            <p>
              If you need to return an item, we would gladly work with you to ensure your complete satisfaction with our service.
            </p>
            <p>
              Clearance, custom-made, and special order products do not qualify for returns.
            </p>
            <p>
              Please email us at customerservice@proskatersplace.com within 60 days of purchase to notify us of the need to return. The originally purchased item must be brand-new (unused) and returned in its original condition, clean, with no signs of use or scratches. Original packaging will be required (if applicable).
            </p>
            <p>
              For any items, a UPS return shipping label can be generated by us and sent via email as an attachment. Once the product is received and inspected, a refund will be issued to the original payment minus the back-and-forth shipping costs (usually $40). If the client can drop off the product at the Toronto store, there is not going to be any return shipping fee. In that case, the product will be inspected on the spot, and a refund will be issued electronically to the original payment within 24 hours, minus the original shipping cost (usually $20). If the client prefers to ship the products by Canada Post or other shipping service at his/her expense to the Toronto shop, an authorization from Customer Service has to be received first, and once the product is received and inspected, a refund will be issued minus the original shipment cost (usually $20).
            </p>
            <p>
              While we understand that mistakes happen and appreciate the fact that you might not like the product as much as it appears in photos, unfortunately, we are unable to cover the shipping costs in case of a return, as while they might be listed as free to you, they are definitely not free to us! We simply dedicate a healthy portion of our profits to cover them. In the event of a return, there are no profits; therefore, we have no choice but to deduct it from the refund. If you are ready to reconsider an exchange, we will be happy to assist you as much as possible.
            </p>
            <p>
              Please kindly let us know the reason for the return, so we can learn and improve for the next time!
            </p>
            <p>
              Please make sure that:
            </p>
            <p>
              Your item should be brand-new and can be sold again as new. Item(s) must be in original packaging without any tags removed. Item(s) cannot be used, scuffed, sharpened, washed, smelling of odor, etc… The packaging is undamaged and complete. No tape, stickers, shipping labels, or other foreign objects should be attached to the box.
            </p>
            <p>
              Any item(s) not meeting the above requirements will not be accepted, and the customer is responsible for the return shipping. A copy of your invoice is helpful but not mandatory.
            </p>
            <h3>CLEARANCE ITEMS POLICY</h3>
            <p>
              Clearance products can not be returned for a refund. Exchange Only! They also do not qualify for free return shipping.
            </p>
            <p>
              If you would like to exchange your item, please email us at customerservice@proskatersplace.com within 30 days of purchase to notify us. The originally purchased item must be brand-new (unused) and returned in its original condition, clean, and with no scratches. Original packaging will be required (if applicable).
            </p>
            <p>
              For any items, we can generate a UPS return shipping label, which will be sent to you via email. Once the product is received and inspected, a replacement will be shipped with the appropriate shipping option to you. Please note that before shipping the item, an invoice for the back-and-forth shipping cost (usually $40) will have to be paid. If the client can exchange the product at the Toronto store, there are not going to be any fees or charges. If the client prefers to ship the products by Canada Post or other shipping service at his/her expense to the Toronto shop, an authorization from Customer Service has to be received first. Once the product is received and inspected, an exchange will be arranged. Client will have to cover the replacement product shipment cost (usually $20).
            </p>
            <p>
              While we understand that mistakes happen and appreciate the fact that you might not like the product as much as in photos, Clearance items are usually sold at cost or even below, and therefore, we are unable to cover any shipping costs associated with exchanges.
            </p>
            <p>
              Any item(s) not meeting the above requirements will not be accepted, and the customer is responsible for the return shipping. A copy of your invoice is helpful but not mandatory.
            </p>
            <h3>EXCHANGE / RETURN SKIS and POLES POLICY</h3>
            <p>
              To prevent damage to skis and ski poles during shipment, returning new skis for a refund or exchange will only be possible when brought to the shop in person. No returns via shipment will be accepted. Please perform all necessary measurements and validations before placing your order online! When a ski is returned for a refund/exchange in-store, a $20 restocking fee will apply. If the ski was shipped to a client and then returned in person for a refund, a $40 (restocking fee + shipment expense) will be deducted from the refunded sum.
            </p>
            <h3>PRICE MATCH POLICY</h3>
            <p>
              At ProSkaters Place, we always strive to provide the best possible prices for our valued customers upfront. If, by accident, you find a lower price for an identical item in a physical store or online before placing an order, please review the rules below to determine if it qualifies for the Price Match. We also offer a 7-day grace period from the original purchase date to apply for a Price Match under the same terms. No price match will be available after that period.
            </p>
            <p>
              The competitor should be a legitimate store or online shop with verifiable contact details and located within North America
            </p>
            <p>
              The product should be identical in all features, size, colors, and other specifications
            </p>
            <p>
              The product and size must be IN STOCK on the competitor's website or in-store (the proof is required if not available for online verification)
            </p>
            <p>
              We will carefully review and verify all the supporting information. Please allow us up to 48 hours to process your request and advise you on our decision. Please note that in some extreme cases, we reserve the right to refuse a price match, and this is only if it would result in a significant loss for us on that sale.
            </p>
            <p>
              The following items DO NOT qualify for the price match:
            </p>
            <p>
              Clearance, closeout, and liquidation items on our website or our competitor's website
            </p>
            <p>
              Products listed on Amazon, Bay.com, Aliexpress, or any other internet selling platform of this type
            </p>
            <p>
              Any client-specific deals, vouchers, and/or one-time promotions offered by a competitor
            </p>
            <p>
              The price match service is not available during storewide promotional periods, such as Boxing Week, Christmas, etc.
            </p>
            <p>
              Please note:
            </p>
            <p>
              The price match will take into account the sale terms, including shipping, delivery fees, rewards, and taxes that might apply from a competitor's website. For example, if the product cost on the competitor's website is $100 and the shipping is an extra $30, the match will be up to $130.
            </p>
            <p>
              Any additional rewards and sales promotions will be waived on price-matched items.
            </p>
            <h3>WARRANTY</h3>
            <p>
              All of the products qualify for a manufacturing warranty against defects accordingly to the specific manufacturer's terms and conditions. ProSkaters Place will gladly represent the client and lead every case to the best possible resolution with the manufacturer. Under no circumstances will ProSkates Place be liable for any claims or fees. We will work with you and for you, but please note that we are merely a reseller and cannot be responsible for manufacturer mistakes.
            </p>
            <h3>CUSTOMIZATION POLICY</h3>
            <p>
              Our shop is one of the very few in the world that provides product customization services. We strive to maintain a sufficient stock of most components, but please note that while we will do our best, we cannot guarantee the availability of customized parts. Incorrect color of the wheels or any other parts on skates, or an upgrade that has not been performed, will not qualify skates for free return shipping for either exchange or return. We will gladly refund the upgrade fee (if it has been charged) and will try to work with you to resolve the issue.
            </p>
            <p>
              ProSkaters Place Inc reserves the right to end or change these terms at any time without prior notice.
            </p>
            <p>
              Effective September 23, 2025.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>